fieldLayouts:
  9f110496-31d1-4cdf-845c-cb242a6fe11a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 1
handle: home
hasTitleField: false
name: Accueil
section: 1d0551e5-3b19-49b8-892d-314b0b1af536 # Accueil
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
