fieldLayouts:
  fae6de2b-6ebe-4ade-b636-779b48f56918:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 2abde05c-e6aa-4e4c-9021-ffa1a26f08ba # Cookie Policy
            instructions: ''
            label: 'Conditions d''utilisation'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 1
      -
        elements:
          -
            fieldUid: efd6f56b-99c9-42ef-ae90-f4658dc521a2 # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: termsService
hasTitleField: true
name: 'Terms of service'
section: e536a215-20fc-4e8e-aeae-4d0d9273e55c # Terms of service
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
