childBlocks: ''
field: 27e3013b-58ea-47ac-893a-9946606fcc55
fieldLayouts:
  cab0c7e5-19ca-4a93-9f6d-cedb89ac9622:
    tabs:
      -
        fields:
          6fa98816-f710-40b3-960e-f19c5b0e45c0:
            required: false
            sortOrder: 1
          19c73d15-31c6-4ed5-bd19-92193123b040:
            required: false
            sortOrder: 3
          92724e80-3861-4082-9481-a26529d9d932:
            required: false
            sortOrder: 2
        name: 'Building Blocks - Content'
        sortOrder: 1
      -
        fields:
          98a640de-6f7f-43ad-acb5-ea73b35e1eac:
            required: false
            sortOrder: 1
          100ecd0f-cfbe-409d-9e41-8a54dce4af68:
            required: false
            sortOrder: 2
          b8482c7f-30b1-48b7-a02b-4f388ced24c0:
            required: false
            sortOrder: 3
        name: 'Building Blocks - Animation'
        sortOrder: 2
handle: header
maxBlocks: 1
maxChildBlocks: 0
name: Header
sortOrder: 2
topLevel: true
