fieldLayouts:
  e3af058b-c347-4a21-a244-3b691e862464:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: documents
hasUrls: true
name: documents
settings:
  path: '@basePath/files/documents'
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@baseUrl/files/documents'
