fieldLayouts:
  cc830699-5a7a-4c9b-a0b7-702177b2462d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsletter
hasUrls: true
name: newsletter
settings:
  path: '@basePath/files/newsletter'
sortOrder: 8
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@baseUrl/files/newsletter'
