columnSuffix: bbewgdca
contentColumnType: string
fieldGroup: 2a67fafe-09dd-4dd9-ba28-37349c423d3b # Policies
handle: policyContactEmail
instructions: ''
name: 'Courriel de contact'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
