columnSuffix: rqqtdqdj
contentColumnType: string(255)
fieldGroup: 2a67fafe-09dd-4dd9-ba28-37349c423d3b # Policies
handle: policyWebsiteUrl
instructions: ''
name: 'URL du site web'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: language
type: craft\fields\Url
