defaultPlacement: end
enableVersioning: false
handle: pageNotFound
name: '404'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5d3331dc-808a-4628-bea6-b5504f0fcf32: # English
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: /404
  451b7d36-f0d8-4860-8bab-eb6756c9a9d6: # Français
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: /404
type: single
