defaultPlacement: end
enableVersioning: false
handle: termsService
name: 'Terms of service'
propagationMethod: all
siteSettings:
  5d3331dc-808a-4628-bea6-b5504f0fcf32: # English
    enabledByDefault: true
    hasUrls: true
    template: _pages/cookie-policy
    uriFormat: terms-of-service
  451b7d36-f0d8-4860-8bab-eb6756c9a9d6: # Français
    enabledByDefault: true
    hasUrls: true
    template: _pages/cookie-policy
    uriFormat: conditions-utilisation
type: single
